services:
  keycloak-mysql:
    container_name: keycloak-mysql_0904
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "5000:3306"  # MySQL을 5000번 포트로 노출
  keycloak:
    container_name: keycloak_0904
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql:5000
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
      - ./docker/keycloak/themes/:/opt/keycloak/themes/
    depends_on:
      - keycloak-mysql
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb_0909
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user-profile
    volumes:
      - ./data/mongodb:/data/db
  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:10.1.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:9000/
      - GF_SERVER_HOME_URL=http://localhost:9000/
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana-client
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=k6hGjcxSmoIbiyWDFeam7Yqy749RtW2q
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid email profile
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=http://localhost:8181/realms/miniblog-realm/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=http://keycloak:8080/realms/miniblog-realm/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=http://keycloak:8080/realms/miniblog-realm/protocol/openid-connect/userinfo
      - GF_AUTH_SIGNOUT_REDIRECT_URL=http://localhost:8181/realms/miniblog-realm/protocol/openid-connect/logout?client_id=grafana-client&post_logout_redirect_uri=http://localhost:9000/login
      - GF_AUTH_OAUTH_AUTO_LOGOUT=true
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(realm_access.roles[*], 'admin') && 'Admin' || (contains(realm_access.roles[*], 'develop') && 'Editor' || 'Viewer')
    ports:
      - '9000:3000'
    depends_on:
      - keycloak